[package]
name = "torxel_engine"
version = "0.0.1"
edition = "2024"
resolver = "2"

[dependencies]

bevy = { version = "0.19.1", features = ["dynamic_linking"] }
avian3d = "0.7" # Avian3D - современная физика для Bevy (аналог PhysX/Bullet)
noise = "0.9"   # Шум Перлина/Simplex для процедурной генерации тора
glam = "0.33.7"   # Векторная математика (уже есть в Bevy, но явно укажем для удобства)


# Dev профиль: быстрая компиляция для итераций
[profile.dev]
opt-level = 1 # Немного оптимизируем, чтобы тесты летали
split-debuginfo = "packed"

# Dev с флагами беви (для динамической линковки)
[profile.dev.package."*"]
opt-level = 3

# Release профиль: МАКСИМАЛЬНАЯ производительность
[profile.release]
opt-level = 3
lto = "thin"       # Link Time Optimization (сквозная оптимизация)
codegen-units = 1  # Максимальная оптимизация кода (долгая сборка)
panic = "abort"    # Меньше размер бинарника, быстрее краш (без unwind)

# Отключаем динамическую линковку в релизе для автономности
[features]
default = ["bevy/dynamic_linking"]
release_build = []